/**
 * MathBridgeJNI.cpp
 * ──────────────────
 * JNI "glue" layer between the JavaFX frontend and the C++ Core Engine.
 *
 * BUILD (Linux/macOS):
 *   g++ -shared -fPIC \
 *       -I"$JAVA_HOME/include" \
 *       -I"$JAVA_HOME/include/linux" \
 *       -I"include/" \
 *       -o build/libmathengine.so \
 *       MathBridgeJNI.cpp CoreEngine.cpp
 *
 * BUILD (Windows):
 *   cl /LD /I"%JAVA_HOME%\include" /I"%JAVA_HOME%\include\win32" \
 *      /Iinclude MathBridgeJNI.cpp CoreEngine.cpp \
 *      /Fe:build\mathengine.dll
 *
 * The header file com_mathengine_jni_MathBridge.h is auto-generated by:
 *   javac -h src/main/cpp/include  MathBridge.java
 * (triggered automatically by the Maven compiler plugin in pom.xml)
 */

#include "include/com_mathengine_jni_MathBridge.h" // auto-generated JNI header
#include "CoreEngine.hpp"                          // your existing C++ engine
#include <string>
#include <stdexcept>

// ── Utility: JNI string ↔ std::string ─────────────────────────────────────────

static std::string jstringToStd(JNIEnv *env, jstring jstr)
{
    if (!jstr)
        return "";
    const char *utf = env->GetStringUTFChars(jstr, nullptr);
    std::string result(utf);
    env->ReleaseStringUTFChars(jstr, utf);
    return result;
}

static jstring stdToJstring(JNIEnv *env, const std::string &str)
{
    return env->NewStringUTF(str.c_str());
}

// ── JNI Implementations ───────────────────────────────────────────────────────

/**
 * Java signature:
 *   private native String nativeCompute(String expression, int precisionFlag);
 *
 * Mangled function name (from javac -h output):
 *   Java_com_mathengine_jni_MathBridge_nativeCompute
 *
 * @param expression   Math query string or "matrix:[[...]]"
 * @param precisionFlag  0 = SYMBOLIC, 1 = NUMERICAL  (maps to PrecisionMode enum)
 */
JNIEXPORT jstring JNICALL
Java_com_mathengine_jni_MathBridge_nativeCompute(
    JNIEnv *env,
    jobject /* this */,
    jstring jExpression,
    jint jPrecisionFlag)
{
    std::string expression = jstringToStd(env, jExpression);
    int flag = static_cast<int>(jPrecisionFlag);

    // Map Java flag to C++ engine precision enum
    // PrecisionMode::SYMBOLIC  = 0
    // PrecisionMode::NUMERICAL = 1
    CoreEngine::PrecisionMode mode =
        (flag == 0) ? CoreEngine::PrecisionMode::SYMBOLIC
                    : CoreEngine::PrecisionMode::NUMERICAL;

    // Safety: reject pathologically long expressions before they reach the engine.
    // The infinite-loop crash (RBRACE without position++) is now fixed in lexer.cpp,
    // but this guard provides defense-in-depth.
    if (expression.size() > 65536)
    {
        jclass excClass = env->FindClass("java/lang/RuntimeException");
        if (excClass)
            env->ThrowNew(excClass, "Expression too long (max 65536 chars)");
        return nullptr;
    }

    try
    {
        // Delegate to the existing core engine
        std::string result = CoreEngine::compute(expression, mode);
        return stdToJstring(env, result);
    }
    catch (const std::bad_alloc &)
    {
        jclass excClass = env->FindClass("java/lang/RuntimeException");
        if (excClass)
            env->ThrowNew(excClass, "C++ out-of-memory in nativeCompute (expression may be too complex)");
        return nullptr;
    }
    catch (const std::exception &ex)
    {
        // Surface C++ exceptions as Java RuntimeExceptions
        jclass excClass = env->FindClass("java/lang/RuntimeException");
        if (excClass)
            env->ThrowNew(excClass, ex.what());
        return nullptr;
    }
    catch (...)
    {
        jclass excClass = env->FindClass("java/lang/RuntimeException");
        if (excClass)
            env->ThrowNew(excClass, "Unknown C++ exception in nativeCompute");
        return nullptr;
    }
}

/**
 * Java signature:
 *   public native String handshakeTest(String input);
 *
 * Bidirectional handshake verification:
 *   Java sends "PING"  →  C++ appends "::PONG"  →  Java receives "PING::PONG"
 * This confirms that strings travel both directions through the JNI bridge
 * without corruption and that the library loaded correctly.
 */
JNIEXPORT jstring JNICALL
Java_com_mathengine_jni_MathBridge_handshakeTest(
    JNIEnv *env,
    jobject /* this */,
    jstring jInput)
{
    std::string input = jstringToStd(env, jInput);
    std::string output = input + "::PONG"; // C++ modification
    return stdToJstring(env, output);
}

/**
 * Java signature:
 *   public native String nativeEngineVersion();
 *
 * Returns a version/build string from the C++ engine for diagnostics.
 */
JNIEXPORT jstring JNICALL
Java_com_mathengine_jni_MathBridge_nativeEngineVersion(
    JNIEnv *env,
    jobject /* this */)
{
    std::string version = CoreEngine::getVersion();
    return stdToJstring(env, version);
}