/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mathengine_jni_MathBridge */

#ifndef _Included_com_mathengine_jni_MathBridge
#define _Included_com_mathengine_jni_MathBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mathengine_jni_MathBridge
 * Method:    nativeCompute
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mathengine_jni_MathBridge_nativeCompute
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mathengine_jni_MathBridge
 * Method:    handshakeTest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mathengine_jni_MathBridge_handshakeTest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mathengine_jni_MathBridge
 * Method:    nativeEngineVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mathengine_jni_MathBridge_nativeEngineVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
