// AbstractAlgebra.cpp

#include "AA.hpp"
#include "../CommonUtils.hpp"

// ── CommonUtils aliases (replaces previous local duplicates) ──────────────────
static auto getP = [](const std::string &j, const std::string &k, const std::string &d = "")
{
    return cu_getStr(j, k, d);
};
static auto getN = [](const std::string &j, const std::string &k, double d = 0.0)
{ return cu_getNum(j, k, d); };
static auto parseVec = [](const std::string &s)
{ return cu_parseVecI(s); };
static auto parseMat = [](const std::string &s)
{ return cu_parseMatI(s); };
static auto fmt = [](double v, int p = 8)
{ return cu_fmt(v, p); };
static auto &str_ll = cu_str;

#include <cmath>
#include <sstream>
#include <algorithm>
#include <numeric>
#include <set>
#include <map>
#include <functional>
#include <stdexcept>

namespace AbstractAlgebra
{

    static AAResult ok(const std::string &v, const std::string &d = "") { return {true, v, d, ""}; }
    static AAResult err(const std::string &m) { return {false, "", "", m}; }

    static long long mod(long long a, long long m) { return ((a % m) + m) % m; }

    // ── Polynomial helpers ────────────────────────────────────────────────────────

    static std::string polyStr(const Poly &p, const std::string &var = "x")
    {
        if (p.empty() || std::all_of(p.begin(), p.end(), [](long long v)
                                     { return v == 0; }))
            return "0";
        std::ostringstream ss;
        bool first = true;
        for (int i = (int)p.size() - 1; i >= 0; --i)
        {
            if (p[i] == 0)
                continue;
            if (!first)
                ss << (p[i] > 0 ? " + " : " - ");
            else if (p[i] < 0)
                ss << "-";
            long long av = std::abs(p[i]);
            if (av != 1 || i == 0)
                ss << av;
            if (i > 0)
                ss << var;
            if (i > 1)
                ss << "^" << i;
            first = false;
        }
        return ss.str();
    }

    static Poly polyNorm(Poly p)
    {
        while (!p.empty() && p.back() == 0)
            p.pop_back();
        return p;
    }

    // ── Groups ────────────────────────────────────────────────────────────────────

    AAResult cyclic(int n)
    {
        std::ostringstream ss;
        ss << "Cyclic Group Z_" << n << "\n";
        ss << "Order: " << n << "\n\n";
        // Generators: elements coprime to n
        ss << "Generators (elements of order " << n << "): {";
        bool first = true;
        for (int k = 1; k < n; ++k)
            if (mcGcd(k, n) == 1)
            {
                if (!first)
                    ss << ",";
                ss << k;
                first = false;
            }
        ss << "}\n\n";
        // Subgroup structure (by Lagrange: one for each divisor of n)
        ss << "Subgroups (one per divisor of n):\n";
        for (int d = 1; d <= n; ++d)
            if (n % d == 0)
            {
                ss << "  Z_" << d << " = {";
                for (int k = 0; k < n; k += n / d)
                    ss << k << (k + n / d < n ? "," : "");
                ss << "} (generated by " << (n / d) % n << ")\n";
            }
        ss << "\nCayley table (mod " << n << ") — top-left 6×6:\n";
        int lim = std::min(n, 6);
        ss << "  ";
        for (int j = 0; j < lim; ++j)
            ss << std::setw(3) << j;
        ss << "\n";
        for (int i = 0; i < lim; ++i)
        {
            ss << std::setw(2) << i << ":";
            for (int j = 0; j < lim; ++j)
                ss << std::setw(3) << (i + j) % n;
            ss << "\n";
        }
        return ok(ss.str());
    }

    AAResult dihedralGroup(int n)
    {
        std::ostringstream ss;
        ss << "Dihedral Group D_" << n << " (symmetries of regular " << n << "-gon)\n";
        ss << "Order: " << 2 * n << "\n\n";
        ss << "Elements: r⁰,r¹,...,r^" << n - 1 << " (rotations) and s,sr,sr²,...,sr^" << n - 1 << " (reflections)\n\n";
        ss << "Relations: rⁿ=e, s²=e, srs⁻¹=r⁻¹\n\n";
        ss << "Centre: ";
        if (n % 2 == 0)
            ss << "{e, r^" << n / 2 << "}\n";
        else
            ss << "{e}\n";
        ss << "Number of conjugacy classes: ";
        if (n % 2 == 0)
            ss << n / 2 + 3 << "\n";
        else
            ss << (n + 3) / 2 << "\n";
        ss << "\nSubgroup lattice:\n";
        ss << "  All rotations form Z_" << n << " (normal subgroup)\n";
        ss << "  " << (n % 2 == 0 ? n + 3 : n) << " dihedral subgroups (including D_d for each d|n)";
        return ok("D_" + cu_str(n) + " order " + cu_str(2 * n), ss.str());
    }

    AAResult symmetricGroup(int n)
    {
        std::ostringstream ss;
        long long ord = 1;
        for (int i = 1; i <= n; ++i)
            ord *= i;
        ss << "Symmetric Group S_" << n << "\n";
        ss << "Order: " << n << "! = " << ord << "\n\n";
        ss << "Normal subgroup: A_" << n << " (alternating, index 2, order " << ord / 2 << ")\n";
        ss << "S_n is solvable for n ≤ 4, simple for n ≥ 5 (A_n is simple)\n\n";
        ss << "Conjugacy classes: partitions of " << n << "\n";
        ss << "Centre: {e} for n ≥ 3\n\n";
        ss << "Generators: transpositions (i,j) or adjacent transpositions (i,i+1)";
        return ok("S_" + cu_str(n) + " order " + cu_str(ord), ss.str());
    }

    AAResult isGroup(const Mat &cayley)
    {
        int n = cayley.size();
        std::ostringstream ss;
        ss << "Group Axiom Verification (Cayley table, n=" << n << ")\n\n";
        // Check closure: all entries in [0,n-1]
        bool closed = true;
        for (auto &row : cayley)
            for (long long v : row)
                if (v < 0 || v >= n)
                {
                    closed = false;
                    break;
                }
        ss << "Closure: " << (closed ? "✓" : "✗") << "\n";
        // Find identity
        int id = -1;
        for (int i = 0; i < n; ++i)
        {
            bool isId = true;
            for (int j = 0; j < n; ++j)
                if (cayley[i][j] != j || cayley[j][i] != j)
                {
                    isId = false;
                    break;
                }
            if (isId)
            {
                id = i;
                break;
            }
        }
        ss << "Identity element: " << (id >= 0 ? cu_str(id) : "none ✗") << (id >= 0 ? " ✓" : "") << "\n";
        // Associativity (check sample triples)
        bool assoc = true;
        for (int i = 0; i < n && assoc; ++i)
            for (int j = 0; j < n && assoc; ++j)
                for (int k = 0; k < n && assoc; ++k)
                    if (cayley[cayley[i][j]][k] != cayley[i][cayley[j][k]])
                        assoc = false;
        ss << "Associativity: " << (assoc ? "✓" : "✗ (not associative)") << "\n";
        // Inverses
        bool inv = true;
        if (id >= 0)
            for (int i = 0; i < n && inv; ++i)
            {
                bool found = false;
                for (int j = 0; j < n; ++j)
                    if (cayley[i][j] == id && cayley[j][i] == id)
                    {
                        found = true;
                        break;
                    }
                if (!found)
                    inv = false;
            }
        ss << "Inverses: " << (inv ? "✓" : "✗") << "\n\n";
        bool isG = closed && id >= 0 && assoc && inv;
        ss << "Conclusion: " << (isG ? "IS a group" : "NOT a group");
        return ok(isG ? "true" : "false", ss.str());
    }

    AAResult isAbelian(const Mat &cayley)
    {
        int n = cayley.size();
        bool ab = true;
        for (int i = 0; i < n && ab; ++i)
            for (int j = 0; j < n && ab; ++j)
                if (cayley[i][j] != cayley[j][i])
                    ab = false;
        return ok(ab ? "true" : "false", ab ? "Group is abelian (commutative)" : "Group is non-abelian");
    }

    AAResult groupOrder(const Mat &cayley)
    {
        // Order of each element = smallest k s.t. a^k = identity
        int n = cayley.size();
        // Find identity
        int id = 0;
        for (int i = 0; i < n; ++i)
        {
            bool ok_ = true;
            for (int j = 0; j < n; ++j)
                if (cayley[i][j] != j)
                {
                    ok_ = false;
                    break;
                }
            if (ok_)
            {
                id = i;
                break;
            }
        }
        std::ostringstream ss;
        ss << "Element orders:\n";
        for (int a = 0; a < n; ++a)
        {
            int cur = a, k = 1;
            while (cur != id && k <= n)
            {
                cur = cayley[cur][a];
                k++;
            }
            ss << "  ord(" << a << ") = " << k << "\n";
        }
        return ok(ss.str());
    }

    AAResult subgroups(int n)
    {
        std::ostringstream ss;
        ss << "Subgroups of Z_" << n << ":\n\n";
        for (int d = 1; d <= n; ++d)
            if (n % d == 0)
            {
                ss << "  <" << n / d << "> = Z_" << d << " = {";
                bool f = true;
                for (int k = 0; k < n; k += n / d)
                {
                    if (!f)
                        ss << ",";
                    ss << k;
                    f = false;
                }
                ss << "}\n";
            }
        return ok(ss.str());
    }

    AAResult quotientGroup(int n, int k)
    {
        if (n % k != 0)
            return err("k must divide n");
        std::ostringstream ss;
        ss << "Z_" << n << " / Z_" << k << " ≅ Z_" << n / k << "\n\n";
        ss << "Cosets of Z_" << k << " in Z_" << n << ":\n";
        for (int i = 0; i < n / k; ++i)
        {
            ss << "  " << i << " + Z_" << k << " = {";
            bool f = true;
            for (int j = 0; j < k; ++j)
            {
                if (!f)
                    ss << ",";
                ss << (i + j * (n / k)) % n;
                f = false;
            }
            ss << "}\n";
        }
        return ok("Z_" + cu_str(n / k), ss.str());
    }

    AAResult directProduct(int m, int n)
    {
        std::ostringstream ss;
        ss << "Z_" << m << " × Z_" << n << "\n";
        ss << "Order: " << m * n << "\n";
        int g = mcGcd(m, n);
        ss << "Structure: " << (g == 1 ? "Z_" + cu_str(m * n) + " (cyclic, since gcd=1)" : "not cyclic, gcd=" + cu_str(g)) << "\n\n";
        ss << "Elements of the form (a,b), a∈Z_" << m << ", b∈Z_" << n << ":\n";
        ss << "Generator orders: lcm(" << m << "," << n << ") = " << m / g * n << "\n";
        ss << "Element (1,1) has order lcm(" << m << "," << n << ") = " << m / g * n << "\n";
        return ok("Z_" + cu_str(m) + "×Z_" + cu_str(n), ss.str());
    }

    AAResult lagrangeThm(int sub, int grp)
    {
        if (grp % sub != 0)
            return err("Subgroup order must divide group order");
        int index = grp / sub;
        std::ostringstream ss;
        ss << "Lagrange's Theorem\n\n";
        ss << "Group order: " << grp << "\n";
        ss << "Subgroup order: " << sub << "\n";
        ss << "Index [G:H] = |G|/|H| = " << index << "\n\n";
        ss << "Consequences:\n";
        ss << "  Every element order divides |G|\n";
        ss << "  Groups of prime order are cyclic\n";
        ss << "  Number of left cosets = index = " << index;
        return ok(cu_str(index), ss.str());
    }

    AAResult conjugacyClasses(const Mat &cayley)
    {
        int n = cayley.size();
        std::vector<int> cls(n, -1);
        int nc = 0;
        // Find identity
        int id = 0;
        for (int i = 0; i < n; ++i)
        {
            bool ok_ = true;
            for (int j = 0; j < n; ++j)
                if (cayley[i][j] != j)
                {
                    ok_ = false;
                    break;
                }
            if (ok_)
            {
                id = i;
                break;
            }
        }
        // Inverse table
        std::vector<int> inv(n);
        for (int i = 0; i < n; ++i)
            for (int j = 0; j < n; ++j)
                if (cayley[i][j] == id)
                {
                    inv[i] = j;
                    break;
                }
        std::ostringstream ss;
        ss << "Conjugacy Classes:\n";
        for (int a = 0; a < n; ++a)
        {
            if (cls[a] >= 0)
                continue;
            std::set<int> cl;
            for (int g = 0; g < n; ++g)
                cl.insert(cayley[cayley[g][a]][inv[g]]);
            for (int e : cl)
                cls[e] = nc;
            ss << "  C_" << nc << " = {";
            bool f = true;
            for (int e : cl)
            {
                if (!f)
                    ss << ",";
                ss << e;
                f = false;
            }
            ss << "}\n";
            nc++;
        }
        ss << "\nNumber of conjugacy classes = " << nc;
        return ok(cu_str(nc), ss.str());
    }

    AAResult centerOfGroup(const Mat &cayley)
    {
        int n = cayley.size();
        std::ostringstream ss;
        ss << "Centre Z(G):\n";
        std::vector<int> center;
        for (int a = 0; a < n; ++a)
        {
            bool inCenter = true;
            for (int g = 0; g < n && inCenter; ++g)
                if (cayley[a][g] != cayley[g][a])
                    inCenter = false;
            if (inCenter)
                center.push_back(a);
        }
        ss << "{";
        bool f = true;
        for (int e : center)
        {
            if (!f)
                ss << ",";
            ss << e;
            f = false;
        }
        ss << "}\n";
        ss << "Order of centre: " << center.size();
        return ok(ss.str());
    }

    AAResult sylow(int p, int n)
    {
        // Count Sylow p-subgroups
        if (n % p != 0)
            return err("p must divide group order");
        int pk = 1, k = 0;
        while (n % p == 0)
        {
            n /= p;
            pk *= p;
            k++;
        }
        int m = n; // m = n/p^k
        // n_p ≡ 1 (mod p) and n_p | m
        std::vector<int> candidates;
        for (int d = 1; d <= m; ++d)
            if (m % d == 0 && d % p == 1)
                candidates.push_back(d);
        std::ostringstream ss;
        ss << "Sylow's Theorems for p=" << p << "\n\n";
        ss << "p^k = " << pk << " (k=" << k << ")\n";
        ss << "m = |G|/p^k = " << m << "\n\n";
        ss << "Sylow p-subgroups have order p^k = " << pk << "\n";
        ss << "Number n_p satisfies: n_p ≡ 1 (mod " << p << ") and n_p | " << m << "\n";
        ss << "Possible values of n_p: {";
        bool f = true;
        for (int c : candidates)
        {
            if (!f)
                ss << ",";
            ss << c;
            f = false;
        }
        ss << "}\n\n";
        ss << "Sylow's theorems:\n";
        ss << "1. Sylow p-subgroups exist\n";
        ss << "2. All Sylow p-subgroups are conjugate\n";
        ss << "3. n_p ≡ 1 (mod p) and n_p | m";
        return ok(ss.str());
    }

    AAResult groupHomomorphism(int m, int n, int phi)
    {
        // φ: Z_m → Z_n defined by φ(1) = phi
        int g = mcGcd(m, n);
        std::ostringstream ss;
        ss << "Group Homomorphism φ: Z_" << m << " → Z_" << n << "\nφ(1) = " << phi << "\n\n";
        ss << "φ(k) = k·" << phi << " mod " << n << "\n\n";
        // Kernel: {k ∈ Z_m : k·phi ≡ 0 (mod n)}
        ss << "Kernel (elements mapping to 0):\n{";
        bool f = true;
        for (int k = 0; k < m; ++k)
            if ((1LL * k * phi) % n == 0)
            {
                if (!f)
                    ss << ",";
                ss << k;
                f = false;
            }
        ss << "}\n\n";
        // Image
        std::set<int> image;
        for (int k = 0; k < m; ++k)
            image.insert((int)((1LL * k * phi) % n));
        ss << "Image: {";
        f = true;
        for (int v : image)
        {
            if (!f)
                ss << ",";
            ss << v;
            f = false;
        }
        ss << "}\n\n";
        bool inj = (phi % n != 0); // kernel = {0} only if n∤phi
        ss << "Injective: " << (inj ? "possibly (check kernel)" : "no (kernel non-trivial)") << "\n";
        ss << "Surjective: " << ((m * phi) % n == 0 && mcGcd(phi, n) == 1 ? "possible" : "check image order");
        return ok(ss.str());
    }

    AAResult commutatorSubgroup(const Mat &cayley)
    {
        int n = cayley.size();
        // [G,G] = subgroup generated by all [a,b] = a^{-1}b^{-1}ab
        int id = 0;
        for (int i = 0; i < n; ++i)
        {
            bool ok_ = true;
            for (int j = 0; j < n; ++j)
                if (cayley[i][j] != j)
                {
                    ok_ = false;
                    break;
                }
            if (ok_)
            {
                id = i;
                break;
            }
        }
        std::vector<int> inv(n);
        for (int i = 0; i < n; ++i)
            for (int j = 0; j < n; ++j)
                if (cayley[i][j] == id)
                {
                    inv[i] = j;
                    break;
                }
        std::set<int> comm;
        for (int a = 0; a < n; ++a)
            for (int b = 0; b < n; ++b)
            {
                int c = cayley[inv[a]][cayley[inv[b]][cayley[a][b]]];
                comm.insert(c);
            }
        // Close under group operations
        bool changed = true;
        while (changed)
        {
            changed = false;
            std::set<int> newComm = comm;
            for (int x : comm)
                for (int y : comm)
                {
                    newComm.insert(cayley[x][y]);
                    if (newComm.size() > comm.size())
                        changed = true;
                }
            comm = newComm;
        }
        std::ostringstream ss;
        ss << "Commutator Subgroup [G,G]:\n{";
        bool f = true;
        for (int e : comm)
        {
            if (!f)
                ss << ",";
            ss << e;
            f = false;
        }
        ss << "}\nOrder: " << comm.size() << "\n";
        ss << "G/[G,G] is the largest abelian quotient (abelianisation)";
        return ok(ss.str());
    }

    // ── Rings ─────────────────────────────────────────────────────────────────────

    AAResult ringZn(int n)
    {
        std::ostringstream ss;
        ss << "Ring Z_" << n << "\n\n";
        ss << "Units (elements with multiplicative inverse):\n{";
        bool f = true;
        std::vector<int> units;
        for (int k = 1; k < n; ++k)
            if (mcGcd(k, n) == 1)
            {
                if (!f)
                    ss << ",";
                ss << k;
                f = false;
                units.push_back(k);
            }
        ss << "}\nφ(n) = " << units.size() << "\n\n";
        ss << "Zero divisors:\n{";
        f = true;
        for (int k = 1; k < n; ++k)
            if (mcGcd(k, n) > 1)
            {
                if (!f)
                    ss << ",";
                ss << k;
                f = false;
            }
        ss << "}\n\n";
        ss << "Z_n is: " << (units.size() == (size_t)(n - 1) ? "a field (n is prime)" : "not a field");
        if (units.size() == (size_t)(n - 1))
            ss << "\nEvery nonzero element is a unit — this is GF(" << n << ")";
        return ok(ss.str());
    }

    AAResult gaussianIntegers(long long a, long long b)
    {
        long long norm = a * a + b * b;
        std::ostringstream ss;
        ss << "Gaussian Integer z = " << a << "+" << b << "i  ∈ Z[i]\n\n";
        ss << "Norm N(z) = |z|² = " << norm << "\n";
        ss << "Conjugate: z̄ = " << a << "-" << b << "i\n\n";
        // Units in Z[i]: ±1, ±i
        ss << "Units of Z[i]: {1, -1, i, -i}\n";
        ss << "z is a unit iff N(z)=1\n";
        ss << "This element: " << (norm == 1 ? "IS a unit" : "not a unit") << "\n\n";
        // Gaussian primes
        bool prime_n = (norm % 4 == 3 && (long long)std::sqrt(norm) == std::sqrt(norm)) ||
                       (b == 0 && a > 0 && norm % 2 == 1);
        // Simple check: if norm is a rational prime ≡ 3 (mod 4) or norm is 2
        ss << "Gaussian prime test:\n";
        ss << "  N(z) = " << norm << "\n";
        ss << "  z is a Gaussian prime if N(z) is a rational prime p ≡ 3 (mod 4),\n";
        ss << "  or z = u·p where p ≡ 3 (mod 4) is rational prime\n";
        return ok(cu_str(norm), ss.str());
    }

    AAResult isIntegralDomain(int n)
    {
        // Z_n is an integral domain iff n is prime
        bool isPrime = true;
        if (n < 2)
            isPrime = false;
        for (int p = 2; p * p <= n; ++p)
            if (n % p == 0)
            {
                isPrime = false;
                break;
            }
        std::ostringstream ss;
        ss << "Z_" << n << " is " << (isPrime ? "" : "NOT ") << "an integral domain\n";
        ss << "(Z_n is an integral domain iff n is prime)\n\n";
        if (!isPrime)
        {
            ss << "Zero divisors present: e.g. ";
            for (int a = 2; a < n; ++a)
                for (int b = 2; b < n; ++b)
                    if ((1LL * a * b) % n == 0)
                    {
                        ss << a << "·" << b << "≡0 (mod " << n << ")";
                        goto done;
                    }
        done:;
        }
        return ok(isPrime ? "true" : "false", ss.str());
    }

    AAResult isField(int n)
    {
        bool isPrime = n >= 2;
        for (int p = 2; p * p <= n; ++p)
            if (n % p == 0)
            {
                isPrime = false;
                break;
            }
        return ok(isPrime ? "true" : "false", "Z_" + cu_str(n) + (isPrime ? " is a field (n prime)" : " is not a field"));
    }

    // ── Polynomial ring operations ────────────────────────────────────────────────

    AAResult polyAdd(const Poly &A, const Poly &B, long long m)
    {
        int sz = std::max(A.size(), B.size());
        Poly C(sz, 0);
        for (int i = 0; i < sz; ++i)
        {
            long long ai = (i < (int)A.size() ? A[i] : 0), bi = (i < (int)B.size() ? B[i] : 0);
            C[i] = ai + bi;
            if (m)
                C[i] = mod(C[i], m);
        }
        C = polyNorm(C);
        return ok(polyStr(C), "(" + polyStr(A) + ") + (" + polyStr(B) + ") = " + polyStr(C) + (m ? " mod " + cu_str(m) : ""));
    }

    AAResult polySub(const Poly &A, const Poly &B, long long m)
    {
        int sz = std::max(A.size(), B.size());
        Poly C(sz, 0);
        for (int i = 0; i < sz; ++i)
        {
            long long ai = (i < (int)A.size() ? A[i] : 0), bi = (i < (int)B.size() ? B[i] : 0);
            C[i] = ai - bi;
            if (m)
                C[i] = mod(C[i], m);
        }
        return ok(polyStr(polyNorm(C)));
    }

    AAResult polyMul(const Poly &A, const Poly &B, long long m)
    {
        if (A.empty() || B.empty())
            return ok("0");
        Poly C(A.size() + B.size() - 1, 0);
        for (int i = 0; i < (int)A.size(); ++i)
            for (int j = 0; j < (int)B.size(); ++j)
            {
                C[i + j] += A[i] * B[j];
                if (m)
                    C[i + j] = mod(C[i + j], m);
            }
        return ok(polyStr(polyNorm(C)));
    }

    AAResult polyDiv(const Poly &A, const Poly &B, long long m)
    {
        if (B.empty() || std::all_of(B.begin(), B.end(), [](long long v)
                                     { return v == 0; }))
            return err("Division by zero polynomial");
        Poly Q, R = A;
        int degB = B.size() - 1;
        while (!R.empty() && (int)R.size() - 1 >= degB)
        {
            int degR = R.size() - 1;
            long long coeff = R.back();
            if (m)
            {
                // Divide leading coeff: need inverse of B.back() mod m
                long long inv_b = 1, bm = B.back() % m, mod_m = m;
                // Extended Euclidean for inverse
                long long old_r = bm, r_ = m, old_s = 1, s_ = 0;
                while (r_)
                {
                    long long q = old_r / r_, tmp = r_;
                    r_ = old_r - q * r_;
                    old_r = tmp;
                    tmp = s_;
                    s_ = old_s - q * s_;
                    old_s = tmp;
                }
                inv_b = mod(old_s, m);
                coeff = mod(coeff * inv_b, m);
            }
            else
                coeff /= B.back();
            Poly term(degR - degB + 1, 0);
            term.back() = coeff;
            auto mul_result = polyMul({coeff}, Poly(term.size() - 1, 0), m); // just for structure
            // Subtract: R -= coeff * x^(degR-degB) * B
            for (int i = 0; i <= (int)B.size() - 1; ++i)
            {
                int idx = degR - degB + i;
                if (idx < (int)R.size())
                {
                    R[idx] -= coeff * B[i];
                    if (m)
                        R[idx] = mod(R[idx], m);
                }
            }
            Q.push_back(coeff);
            while (!R.empty() && R.back() == 0)
                R.pop_back();
        }
        std::reverse(Q.begin(), Q.end());
        std::ostringstream ss;
        ss << "Quotient: " << polyStr(polyNorm(Q)) << "\nRemainder: " << (R.empty() ? "0" : polyStr(R));
        return ok(ss.str());
    }

    AAResult polyEval(const Poly &A, long long x_, long long m)
    {
        long long result = 0, xpow = 1;
        for (int i = 0; i < (int)A.size(); ++i)
        {
            result += A[i] * xpow;
            if (m)
                result = mod(result, m);
            xpow *= x_;
            if (m)
                xpow = mod(xpow, m);
        }
        std::ostringstream ss;
        ss << polyStr(A) << " evaluated at x=" << x_ << (m ? " mod " + cu_str(m) : "") << " = " << result;
        return ok(cu_str(result), ss.str());
    }

    AAResult polyGCD(const Poly &A, const Poly &B, long long m)
    {
        Poly a = polyNorm(A), b = polyNorm(B);
        while (!b.empty())
        {
            // a = q*b + r
            auto res = polyDiv(a, b, m);
            // Extract remainder from detail
            // Simple: implement directly
            Poly R = a;
            int degB = b.size() - 1;
            while (!R.empty() && (int)R.size() - 1 >= degB)
            {
                int degR = R.size() - 1;
                long long coeff = R.back();
                if (m)
                    coeff = mod(coeff, m);
                if (b.back() != 0)
                {
                    if (m)
                    {
                        long long old_r = mod(b.back(), m), r_ = m, old_s = 1, s_ = 0;
                        while (r_)
                        {
                            long long q = old_r / r_, tmp = r_;
                            r_ = old_r - q * r_;
                            old_r = tmp;
                            tmp = s_;
                            s_ = old_s - q * s_;
                            old_s = tmp;
                        }
                        coeff = mod(coeff * mod(old_s, m), m);
                    }
                    else
                        coeff /= b.back();
                }
                for (int i = 0; i < (int)b.size(); ++i)
                {
                    int idx = degR - degB + i;
                    if (idx < (int)R.size())
                    {
                        R[idx] -= coeff * b[i];
                        if (m)
                            R[idx] = mod(R[idx], m);
                    }
                }
                while (!R.empty() && R.back() == 0)
                    R.pop_back();
            }
            a = b;
            b = polyNorm(R);
        }
        // Normalise leading coefficient
        if (!a.empty() && a.back() != 1 && m)
        {
            long long inv = 1, bv = a.back(), old_r = bv, r_ = m, old_s = 1, s_ = 0;
            while (r_)
            {
                long long q = old_r / r_, tmp = r_;
                r_ = old_r - q * r_;
                old_r = tmp;
                tmp = s_;
                s_ = old_s - q * s_;
                old_s = tmp;
            }
            inv = mod(old_s, m);
            for (auto &c : a)
            {
                c = mod(c * inv, m);
            }
        }
        return ok(polyStr(polyNorm(a)), "gcd = " + polyStr(polyNorm(a)));
    }

    AAResult polyIrreducible(const Poly &A, long long p)
    {
        int deg = A.size() - 1;
        if (deg < 1)
            return err("Need degree ≥ 1");
        std::ostringstream ss;
        ss << "Irreducibility test for " << polyStr(A) << " over GF(" << p << ")\n\n";
        // Test: no roots in GF(p)
        bool hasRoot = false;
        int rootVal = -1;
        for (int x = 0; x < p; ++x)
        {
            auto ev = polyEval(A, x, p);
            if (std::stoll(ev.value) == 0)
            {
                hasRoot = true;
                rootVal = x;
                break;
            }
        }
        if (hasRoot)
        {
            ss << "Root found: x=" << rootVal << "\n(p(" << rootVal << ")=0 mod " << p << ")\nPolynomial is REDUCIBLE";
        }
        else
        {
            if (deg <= 2)
                ss << "No roots in GF(" << p << ") and deg≤2 → IRREDUCIBLE";
            else
                ss << "No roots in GF(" << p << "). For deg>" << 2 << " also check for quadratic factors.\n(Implement factor search for complete test)";
        }
        return ok(hasRoot ? "false" : "true", ss.str());
    }

    AAResult polyCyclotomic(int n)
    {
        // Compute nth cyclotomic polynomial Φ_n(x)
        // Φ_n = ∏_{d|n} (x^d - 1)^{μ(n/d)}  — via Möbius inversion
        // Simpler: Φ_n(x) = ∏_{gcd(k,n)=1, 1≤k≤n} (x - e^{2πik/n})
        // For small n, build directly
        std::ostringstream ss;
        ss << "Cyclotomic Polynomial Φ_" << n << "(x)\n\n";
        // Known values
        static const std::map<int, std::string> known = {
            {1, "x-1"}, {2, "x+1"}, {3, "x^2+x+1"}, {4, "x^2+1"}, {5, "x^4+x^3+x^2+x+1"}, {6, "x^2-x+1"}, {8, "x^4+1"}, {10, "x^4-x^3+x^2-x+1"}, {12, "x^4-x^2+1"}};
        if (known.count(n))
            ss << "Φ_" << n << "(x) = " << known.at(n) << "\n";
        else
            ss << "Φ_" << n << "(x) computed via: Φ_n = (x^n-1) / ∏_{d|n,d<n} Φ_d(x)\n";
        ss << "\nDegree: φ(" << n << ") = ";
        long long phi = n;
        int m = n;
        for (long long p = 2; p * p <= m; ++p)
            if (m % p == 0)
            {
                while (m % p == 0)
                    m /= p;
                phi -= phi / p;
            }
        if (m > 1)
            phi -= phi / m;
        ss << phi << "\n";
        ss << "Roots: primitive " << n << "th roots of unity e^{2πik/n}, gcd(k,n)=1";
        return ok("Φ_" + cu_str(n), ss.str());
    }

    AAResult galoisField(int p, int n)
    {
        std::ostringstream ss;
        long long order = 1;
        for (int i = 0; i < n; ++i)
            order *= p;
        ss << "Galois Field GF(" << p << "^" << n << ") = GF(" << order << ")\n\n";
        ss << "Construction: GF(p^n) = GF(p)[x]/(f(x))\n";
        ss << "where f(x) is an irreducible polynomial of degree " << n << " over GF(" << p << ")\n\n";
        ss << "Properties:\n";
        ss << "  Order (number of elements): " << order << "\n";
        ss << "  Characteristic: " << p << "\n";
        ss << "  Multiplicative group: cyclic of order " << order - 1 << "\n";
        ss << "  Subfields: GF(p^d) for each d dividing n\n\n";
        ss << "GF(" << order << ")* is generated by a primitive element α\n";
        ss << "where α is a root of the minimal irreducible polynomial over GF(" << p << ")";
        return ok("GF(" + cu_str(order) + ")", ss.str());
    }

    AAResult multiplicativeOrder(long long a, long long p)
    {
        // Order of a in GF(p)* = smallest k s.t. a^k ≡ 1 (mod p)
        if (a % p == 0)
            return err("a ≡ 0 (mod p): no multiplicative order");
        long long cur = a % p, k = 1;
        while (cur != 1 && k <= p)
        {
            cur = cur * (a % p) % p;
            k++;
        }
        std::ostringstream ss;
        ss << "Multiplicative order of " << a << " in GF(" << p << ")*\n";
        ss << "ord(" << a << ") = " << k << "\n";
        ss << "(smallest k s.t. " << a << "^k ≡ 1 (mod " << p << "))";
        return ok(cu_str(k), ss.str());
    }

    AAResult primitiveElementGF(int p)
    {
        // Find smallest generator of (Z/pZ)*
        for (int g = 2; g < p; ++g)
        {
            long long cur = g, ord = 1;
            while (cur != 1)
            {
                cur = cur * g % p;
                ord++;
            }
            if (ord == p - 1)
                return ok(cu_str(g), cu_str(g) + " is a primitive root mod " + cu_str(p) + " (order " + cu_str(p - 1) + ")");
        }
        return err("No primitive root found");
    }

    // ── Permutations ──────────────────────────────────────────────────────────────

    AAResult permCycleNotation(const Vec &perm)
    {
        int n = perm.size();
        std::vector<bool> visited(n, false);
        std::ostringstream ss;
        ss << "Cycle notation of σ = [";
        for (int i = 0; i < n; ++i)
        {
            if (i)
                ss << ",";
            ss << perm[i];
        }
        ss << "]\n\n";
        bool isId = true;
        for (int i = 0; i < n; ++i)
            if (!visited[i])
            {
                if (perm[i] == i)
                {
                    visited[i] = true;
                    continue;
                }
                isId = false;
                ss << "(";
                int cur = i;
                while (!visited[cur])
                {
                    visited[cur] = true;
                    ss << cur;
                    cur = perm[cur];
                    if (!visited[cur])
                        ss << " ";
                }
                ss << ")";
            }
        if (isId)
            ss << "(e)  [identity]";
        return ok(ss.str());
    }

    AAResult permOrder(const Vec &perm)
    {
        int n = perm.size();
        std::vector<bool> visited(n, false);
        long long ord = 1;
        for (int i = 0; i < n; ++i)
            if (!visited[i] && perm[i] != i)
            {
                int len = 0, cur = i;
                while (!visited[cur])
                {
                    visited[cur] = true;
                    cur = perm[cur];
                    len++;
                }
                ord = ord / mcGcd(ord, len) * len;
            }
        return ok(cu_str(ord), "Order of permutation = lcm of cycle lengths = " + cu_str(ord));
    }

    AAResult permCompose(const Vec &p, const Vec &q)
    {
        int n = p.size();
        Vec pq(n);
        for (int i = 0; i < n; ++i)
            pq[i] = p[q[i]];
        std::ostringstream ss;
        ss << "σ∘τ = [";
        for (int i = 0; i < n; ++i)
        {
            if (i)
                ss << ",";
            ss << pq[i];
        }
        ss << "]";
        return ok(ss.str());
    }

    AAResult permInverse(const Vec &perm)
    {
        int n = perm.size();
        Vec inv(n);
        for (int i = 0; i < n; ++i)
            inv[perm[i]] = i;
        std::ostringstream ss;
        ss << "σ⁻¹ = [";
        for (int i = 0; i < n; ++i)
        {
            if (i)
                ss << ",";
            ss << inv[i];
        }
        ss << "]";
        return ok(ss.str());
    }

    AAResult permParity(const Vec &perm)
    {
        int n = perm.size(), inversions = 0;
        for (int i = 0; i < n; ++i)
            for (int j = i + 1; j < n; ++j)
                if (perm[i] > perm[j])
                    inversions++;
        bool even = (inversions % 2 == 0);
        std::ostringstream ss;
        ss << "Number of inversions: " << inversions << "\n";
        ss << "Permutation is " << (even ? "even (∈ A_n)" : "odd (∉ A_n)");
        return ok(even ? "even" : "odd", ss.str());
    }

    AAResult permConjugate(const Vec &p, const Vec &q)
    {
        // Compute q p q^{-1}
        int n = p.size();
        Vec qinv(n);
        for (int i = 0; i < n; ++i)
            qinv[q[i]] = i;
        Vec result(n);
        for (int i = 0; i < n; ++i)
            result[i] = q[p[qinv[i]]];
        std::ostringstream ss;
        ss << "q σ q⁻¹ = [";
        for (int i = 0; i < n; ++i)
        {
            if (i)
                ss << ",";
            ss << result[i];
        }
        ss << "]";
        return ok(ss.str());
    }

    // ── Dispatch ──────────────────────────────────────────────────────────────────
    static long long getN(const std::string &j, const std::string &k, long long d = 0)
    {
        auto v = getP(j, k);
        if (v.empty())
            return d;
        try
        {
            return std::stoll(v);
        }
        catch (...)
        {
            return d;
        }
    }
    static Poly parsePoly(const std::string &s)
    {
        Poly v;
        std::string t = s;
        if (!t.empty() && t.front() == '[')
            t = t.substr(1, t.size() - 2);
        std::istringstream ss(t);
        std::string tok;
        while (std::getline(ss, tok, ','))
            try
            {
                v.push_back(std::stoll(tok));
            }
            catch (...)
            {
            }
        return v;
    }

    // =============================================================================
    // MISSING ABSTRACT ALGEBRA IMPLEMENTATIONS
    // =============================================================================

    AAResult burnside(const std::vector<Vec> &orbits)
    {
        // Burnside's lemma: |X/G| = (1/|G|) Σ_{g∈G} |Fix(g)|
        // orbits[i] = fixed-point set of group element i
        int G = orbits.size();
        long long totalFixed = 0;
        for (auto &fix : orbits)
            totalFixed += fix.size();
        std::ostringstream ss;
        ss << "Burnside's Lemma  |X/G| = (1/|G|) Σ|Fix(g)|";
        ss << "|G| = " << G << " ";
        for (int i = 0; i < G; ++i)
        {
            ss << "  |Fix(g_" << i << ")| = " << orbits[i].size() << " ";
        }
        long long orbCount = (G > 0) ? totalFixed / G : 0;
        ss << "Σ | Fix(g) | = " << totalFixed << " ";
        ss << "Number of distinct orbits = " << totalFixed << "/" << G << " = " << orbCount;
        return ok(cu_str(orbCount), ss.str());
    }

    AAResult chineseRemainderRing(const Vec &mods)
    {
        // Z_{m1} × Z_{m2} × ... ≅ Z_{m1·m2·...} when pairwise coprime
        std::ostringstream ss;
        ss << "Chinese Remainder Theorem for Rings";
        long long product = 1;
        bool coprime = true;
        for (size_t i = 0; i < mods.size(); ++i)
        {
            product *= mods[i];
            for (size_t j = i + 1; j < mods.size(); ++j)
            {
                if (mcGcd(mods[i], mods[j]) != 1)
                {
                    coprime = false;
                }
            }
        }
        ss << "Moduli: {";
        for (size_t i = 0; i < mods.size(); ++i)
        {
            if (i)
                ss << ",";
            ss << mods[i];
        }
        ss << "}";
        ss << "Product: " << product << " ";
        ss << "Pairwise coprime: " << (coprime ? "YES" : "NO") << " ";
        if (coprime)
        {
            ss << "CRT: Z_" << product << " ≅ ";
            for (size_t i = 0; i < mods.size(); ++i)
            {
                if (i)
                    ss << " × ";
                ss << "Z_" << mods[i];
            }
            ss << "(Ring isomorphism)";
            ss << "Projection maps: Z_" << product << " → Z_" << mods[0];
            ss << " is x ↦ x mod " << mods[0];
        }
        else
        {
            ss << "Moduli not pairwise coprime — CRT does NOT give ring isomorphism.";
            ss << "Isomorphism holds iff all pairs gcd = 1.";
        }
        return ok(coprime ? "isomorphic" : "not isomorphic", ss.str());
    }

    AAResult fieldCharacteristic(int p, int n)
    {
        std::ostringstream ss;
        ss << "Characteristic of GF(" << p << "^" << n << ")";
        ss << "The characteristic of a field is the smallest positive integer m";
        ss << "such that m·1 = 0  (or 0 if no such m exists)";
        ss << "For GF(p^n): characteristic = p = " << p << " ";
        ss << "Since GF(p^n) has characteristic p: ";
        ss << "  x + x + ... + x (p times) = 0 for all x";
        ss << "  (a + b)^p = a^p + b^p  (Frobenius endomorphism)";
        ss << "  Frobenius map φ: x ↦ x^p is a field automorphism";
        ss << "The Galois group Gal(GF(p^n)/GF(p)) = ⟨φ⟩ ≅ Z_" << n;
        return ok(cu_str(p), ss.str());
    }

    AAResult idealGenerated(int n, int generator)
    {
        std::ostringstream ss;
        ss << "Ideal (" << generator << ") in Z_" << n << " ";
        int g = mcGcd(generator, n);
        ss << "In Z_n, ideals are of the form (d) = d·Z_n for d | n";
        ss << "gcd(" << generator << ", " << n << ") = " << g << " ";
        ss << "(" << generator << ") = (" << g << ") = {";
        bool first = true;
        for (int k = 0; k < n; k += g)
        {
            if (!first)
                ss << ", ";
            ss << k;
            first = false;
        }
        ss << "}";
        ss << "This ideal has " << n / g << " elements.";
        ss << "Z_n / (" << generator << ") ≅ Z_" << g;
        return ok("(" + cu_str(generator) + ") = (" + cu_str(g) + ")", ss.str());
    }

    AAResult orbitStabiliser(const Mat &cayley, int element)
    {
        int n = cayley.size();
        if (element >= n)
            return err("Element out of range");
        std::ostringstream ss;
        ss << "Orbit-Stabiliser Theorem for element " << element << " ";
        // The stabiliser Stab(x) = {g ∈ G : g·x = x}
        // For a group acting on itself by conjugation: Stab(x) = centraliser C(x)
        std::vector<int> stab;
        int id = 0;
        for (int i = 0; i < n; ++i)
        {
            bool isId = true;
            for (int j = 0; j < n; ++j)
                if (cayley[i][j] != j)
                {
                    isId = false;
                    break;
                }
            if (isId)
            {
                id = i;
                break;
            }
        }
        std::vector<int> inv(n);
        for (int i = 0; i < n; ++i)
            for (int j = 0; j < n; ++j)
                if (cayley[i][j] == id)
                    inv[i] = j;
        std::set<int> orbit;
        for (int g = 0; g < n; ++g)
        {
            int conj = cayley[cayley[g][element]][inv[g]];
            orbit.insert(conj);
            if (conj == element)
                stab.push_back(g);
        }
        ss << "Orbit of " << element << " (under conjugation): {";
        bool f = true;
        for (int e : orbit)
        {
            if (!f)
                ss << ",";
            ss << e;
            f = false;
        }
        ss << "}";
        ss << "Stabiliser Stab(" << element << "): {";
        f = true;
        for (int s : stab)
        {
            if (!f)
                ss << ",";
            ss << s;
            f = false;
        }
        ss << "}";
        ss << "|Orbit| × |Stab| = " << orbit.size() << " × " << stab.size() << " = " << orbit.size() * stab.size() << " = |G| = " << n << " ";
        ss << "(Orbit-Stabiliser theorem: |Orb(x)| · |Stab(x)| = |G|)";
        return ok(ss.str());
    }

    AAResult polyEuclid(const Poly &A, const Poly &B, long long p)
    {
        std::ostringstream ss;
        ss << "Extended Euclidean Algorithm for polynomials over GF(" << p << ")";
        ss << "A = " << polyStr(A) << " ";
        ss << "B = " << polyStr(B) << " ";
        ss << "Finds gcd(A,B) and u,v such that u·A + v·B = gcd";

        auto gcd_result = polyGCD(A, B, p);
        ss << "gcd(A,B) = " << gcd_result.value << " ";
        ss << "Back-substitution (Bezout identity) from the division steps: ";
        ss << "Compute via back-substitution in the Euclidean remainder sequence.";
        ss << "(Full implementation: maintain coefficient polynomials through each step)";
        return ok(gcd_result.value, ss.str());
    }

    AAResult polyFactor(const Poly &A, long long p)
    {
        std::ostringstream ss;
        ss << "Factorisation of " << polyStr(A) << " over GF(" << p << ")";
        int deg = (int)A.size() - 1;
        if (deg <= 0)
            return ok("constant", "No nontrivial factors");

        Poly rem = A;
        std::vector<std::pair<Poly, int>> factors;
        ss << "Trial division by degree-1 factors (x - a), a ∈ GF(" << p << "): ";
        for (long long a = 0; a < p; ++a)
        {
            int mult = 0;
            while (true)
            {
                auto ev = polyEval(rem, a, p);
                if (std::stoll(ev.value) != 0)
                    break;
                // (x - a) divides rem: perform synthetic division
                Poly factor = {mod(-a, p), 1};
                auto divres = polyDiv(rem, factor, p);
                Poly quot;
                long long cur_lead = rem.back();
                Poly r2 = rem;
                Poly q;
                while ((int)r2.size() - 1 >= 1)
                {
                    long long coeff = r2.back();
                    q.insert(q.begin(), mod(coeff, p));
                    r2.pop_back();
                    if (!r2.empty())
                        r2.back() = mod(r2.back() + coeff * a, p);
                }
                rem = q;
                mult++;
            }
            if (mult > 0)
            {
                factors.push_back({{mod(-a, p), 1}, mult});
                ss << "  (x - " << a << ")^" << mult << " ";
            }
        }
        if (!rem.empty() && (int)rem.size() - 1 > 0)
        {
            ss << "  Remaining irreducible factor: " << polyStr(rem) << " ";
        }
        if (factors.empty() && ((int)rem.size() - 1 == deg))
        {
            ss << "  Polynomial is irreducible over GF(" << p << ")";
        }
        return ok(ss.str());
    }

    AAResult quotientRing(int n, int ideal)
    {
        // Z_n / (ideal): quotient ring
        int g = mcGcd(ideal, n);
        int quotient_order = g; // |(ideal)| = n/g, so |Z_n/(ideal)| = g
        std::ostringstream ss;
        ss << "Quotient Ring Z_" << n << " / (" << ideal << ")";
        ss << "The ideal (" << ideal << ") in Z_" << n << " = (" << g << ") has order " << n / g << " ";
        ss << "Quotient ring order = |Z_" << n << "| / |(" << g << ")| = " << n << "/" << n / g << " = " << quotient_order << " ";
        ss << "Z_" << n << " / (" << g << ") ≅ Z_" << g << " ";
        ss << "Cosets: ";
        for (int i = 0; i < g; ++i)
        {
            ss << "  " << i << " + (" << g << ") = {";
            bool f = true;
            for (int k = 0; k < n; k += g)
            {
                if (!f)
                    ss << ",";
                ss << (i + k) % n;
                f = false;
            }
            ss << "}";
        }
        return ok("Z_" + cu_str(g), ss.str());
    }

    AAResult fieldExtension(int p, const Poly &minPoly)
    {
        std::ostringstream ss;
        ss << "Field Extension GF(" << p << ")[x]/(" << polyStr(minPoly) << ")\n\n";
        ss << "This quotient ring is a field iff " << polyStr(minPoly) << " is irreducible over GF(" << p << ")\n\n";
        auto irr = polyIrreducible(minPoly, p);
        ss << "Irreducibility check: " << irr.value << "\n\n";
        int deg = minPoly.size() - 1;
        long long fieldSize = 1;
        for (int i = 0; i < deg; ++i)
            fieldSize *= p;
        ss << "If irreducible: field has " << p << "^" << deg << " = " << fieldSize << " elements\n";
        ss << "Elements: polynomials of degree < " << deg << " over GF(" << p << ")\n";
        ss << "Arithmetic: add/multiply polynomials, reduce mod (" << polyStr(minPoly) << ") and mod " << p;
        return ok(ss.str());
    }

    AAResult dispatch(const std::string &op, const std::string &json)
    {
        try
        {
            if (op == "cyclic")
                return cyclic((int)getN(json, "n"));
            if (op == "dihedral")
                return dihedralGroup((int)getN(json, "n"));
            if (op == "symmetric")
                return symmetricGroup((int)getN(json, "n"));
            if (op == "is_group")
                return isGroup(cu_parseMatI(getP(json, "table")));
            if (op == "is_abelian")
                return isAbelian(parseMat(getP(json, "table")));
            if (op == "group_order")
                return groupOrder(parseMat(getP(json, "table")));
            if (op == "subgroups")
                return subgroups((int)getN(json, "n"));
            if (op == "quotient_group")
                return quotientGroup((int)getN(json, "n"), (int)getN(json, "k"));
            if (op == "direct_product")
                return directProduct((int)getN(json, "m"), (int)getN(json, "n"));
            if (op == "lagrange")
                return lagrangeThm((int)getN(json, "sub"), (int)getN(json, "grp"));
            if (op == "conjugacy")
                return conjugacyClasses(parseMat(getP(json, "table")));
            if (op == "center")
                return centerOfGroup(parseMat(getP(json, "table")));
            if (op == "commutator")
                return commutatorSubgroup(parseMat(getP(json, "table")));
            if (op == "sylow")
                return sylow((int)getN(json, "p"), (int)getN(json, "n"));
            if (op == "hom")
                return groupHomomorphism((int)getN(json, "m"), (int)getN(json, "n"), (int)getN(json, "phi"));
            if (op == "ring_zn")
                return ringZn((int)getN(json, "n"));
            if (op == "gaussian_int")
                return gaussianIntegers(getN(json, "a"), getN(json, "b"));
            if (op == "is_int_domain")
                return isIntegralDomain((int)getN(json, "n"));
            if (op == "is_field_aa")
                return isField((int)getN(json, "n"));
            if (op == "poly_add")
                return polyAdd(parsePoly(getP(json, "A")), parsePoly(getP(json, "B")), getN(json, "mod"));
            if (op == "poly_sub")
                return polySub(parsePoly(getP(json, "A")), parsePoly(getP(json, "B")), getN(json, "mod"));
            if (op == "poly_mul")
                return polyMul(parsePoly(getP(json, "A")), parsePoly(getP(json, "B")), getN(json, "mod"));
            if (op == "poly_div")
                return polyDiv(parsePoly(getP(json, "A")), parsePoly(getP(json, "B")), getN(json, "mod"));
            if (op == "poly_gcd")
                return polyGCD(parsePoly(getP(json, "A")), parsePoly(getP(json, "B")), getN(json, "mod"));
            if (op == "poly_eval")
                return polyEval(parsePoly(getP(json, "poly")), getN(json, "x"), getN(json, "mod"));
            if (op == "poly_irred")
                return polyIrreducible(parsePoly(getP(json, "poly")), getN(json, "p"));
            if (op == "cyclotomic")
                return polyCyclotomic((int)getN(json, "n"));
            if (op == "galois_field")
                return galoisField((int)getN(json, "p"), (int)getN(json, "n", 1));
            if (op == "mult_order")
                return multiplicativeOrder(getN(json, "a"), getN(json, "p"));
            if (op == "prim_element")
                return primitiveElementGF((int)getN(json, "p"));
            if (op == "perm_cycle")
                return permCycleNotation(parseVec(getP(json, "perm")));
            if (op == "perm_order")
                return permOrder(parseVec(getP(json, "perm")));
            if (op == "perm_compose")
                return permCompose(parseVec(getP(json, "p")), parseVec(getP(json, "q")));
            if (op == "perm_inverse")
                return permInverse(parseVec(getP(json, "perm")));
            if (op == "perm_parity")
                return permParity(parseVec(getP(json, "perm")));
            if (op == "perm_conjugate")
                return permConjugate(parseVec(getP(json, "p")), parseVec(getP(json, "q")));
            if (op == "field_ext")
                return fieldExtension((int)getN(json, "p"), parsePoly(getP(json, "minpoly")));
            if (op == "burnside")
            {
                std::vector<Vec> orbits;
                auto raw = getP(json, "orbits");
                size_t pos = 0;
                while ((pos = raw.find('[', pos)) != std::string::npos)
                {
                    ++pos;
                    size_t end = raw.find(']', pos);
                    if (end == std::string::npos)
                        break;
                    Vec r = parseVec("[" + raw.substr(pos, end - pos) + "]");
                    orbits.push_back(r);
                    pos = end + 1;
                }
                return burnside(orbits);
            }
            if (op == "crt_ring")
                return chineseRemainderRing(parseVec(getP(json, "mods")));
            if (op == "field_char")
                return fieldCharacteristic((int)getN(json, "p"), (int)getN(json, "n", 1));
            if (op == "ideal_gen")
                return idealGenerated((int)getN(json, "n"), (int)getN(json, "gen"));
            if (op == "orbit_stab")
                return orbitStabiliser(parseMat(getP(json, "table")), (int)getN(json, "element"));
            if (op == "poly_euclid")
                return polyEuclid(parsePoly(getP(json, "A")), parsePoly(getP(json, "B")), getN(json, "p", 2));
            if (op == "poly_factor")
                return polyFactor(parsePoly(getP(json, "poly")), getN(json, "p", 2));
            if (op == "quotient_ring")
                return quotientRing((int)getN(json, "n"), (int)getN(json, "ideal"));

            return err("Unknown abstract algebra operation: " + op);
        }
        catch (const std::exception &e)
        {
            return err(e.what());
        }
    }

} // namespace AbstractAlgebra